### ISSUE TITLE
Improving the ID plot to including stacked bar plot and group to different factors

### ISSUE THREAD

**Issue by xiaofengxie128** [RTKlab-BYU/SCP_LF#2]
Add options for more complicated ID plots:

1. Stacked plots (e.g., stack MS2 and MBR on top of each other)
2. Regroup sample groups into big groups (as shown below)

![image](https://user-images.githubusercontent.com/77813931/229226708-5f4af1d3-080b-4968-bc47-f3f653268764.png)

**Comment by kwebber3** [comment]
Working in #14
